### ISSUE TITLE
Selligent.InAppContents.Html.Card reference can't be linked

### ISSUE THREAD

**Issue by nickvkaam** [SelligentMarketingCloud/MobileSDK-Android#1]
Using android studio 3.4.1 with Gradle 5.1.1 using Selligent Mobile SDK 2.1.2 from JCenter won't allow me to build. It exits with the following errors:

`Android resource linking failed
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1803: error: style attribute 'attr/cardBackgroundColor (aka com.yourzine.selligentmobilesdk_poc:attr/cardBackgroundColor)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1804: error: style attribute 'attr/cardCornerRadius (aka com.yourzine.selligentmobilesdk_poc:attr/cardCornerRadius)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1805: error: style attribute 'attr/cardElevation (aka com.yourzine.selligentmobilesdk_poc:attr/cardElevation)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1806: error: style attribute 'attr/cardMaxElevation (aka com.yourzine.selligentmobilesdk_poc:attr/cardMaxElevation)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1807: error: style attribute 'attr/cardPreventCornerOverlap (aka com.yourzine.selligentmobilesdk_poc:attr/cardPreventCornerOverlap)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1808: error: style attribute 'attr/cardUseCompatPadding (aka com.yourzine.selligentmobilesdk_poc:attr/cardUseCompatPadding)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1809: error: style attribute 'attr/contentPadding (aka com.yourzine.selligentmobilesdk_poc:attr/contentPadding)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1810: error: style attribute 'attr/contentPaddingBottom (aka com.yourzine.selligentmobilesdk_poc:attr/contentPaddingBottom)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1811: error: style attribute 'attr/contentPaddingLeft (aka com.yourzine.selligentmobilesdk_poc:attr/contentPaddingLeft)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1812: error: style attribute 'attr/contentPaddingRight (aka com.yourzine.selligentmobilesdk_poc:attr/contentPaddingRight)' not found.
D:\Projects\SelligentMobileSDKpoc\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:1813: error: style attribute 'attr/contentPaddingTop (aka com.yourzine.selligentmobilesdk_poc:attr/contentPaddingTop)' not found.
error: failed linking references.`

**Comment by Selligent** [comment]
Hi

You need to add the following dependency:
com.android.support:cardview-v7

Kind regards

Frédéric

**Comment by fabiosassu-sysdata** [comment]
To be honest, I think this should be written in the README: it costed me at least three hours to figure out what the issue was.

**Comment by Novajox** [comment]
Hello here, I have the same error. 

We use version 3.0 of selligent.

I tested with 
    implementation "androidx.cardview:cardview:1.0.0"
and then 
com.android.support:cardview-v7:28.0.0


Now we have 

AAPT: error: resource style/Theme.AppCompat.Dialog (aka com.santevet.selligent.test:style/Theme.AppCompat.Dialog) not found.
error: resource style/Theme.AppCompat (aka com.santevet.selligent.test:style/Theme.AppCompat) not found.
error: resource style/Theme.AppCompat.Light (aka com.santevet.selligent.test:style/Theme.AppCompat.Light) not found.
error: failed linking references.

**Comment by Selligent** [comment]
Hi

It should be 'androidx.cardview:cardview' and 'androidx.appcompat:appcompat' if you are using versions 3.0 and above.
Although, the appcompat one shouldn't be needed.
(sorry for the late answer but this channel is not monitored, it is best to log tickets with Selligent).

Kind regards,

Frédéric
