### ISSUE TITLE
Android - Proguard

### ISSUE THREAD

**Issue by samirma** [SelligentMarketingCloud/MobileSDK-Android#5]
According to the manual you should add this line into the proguard file:

`
-keep class com.google.firebase.iid.FirebaseInstanceId { *; }
`

but it doesn't work, the api code calls com.google.firebase.messaging.FirebaseMessaging, it was need to add the follwing line to get the Selligent working:

`
-keep class com.google.firebase.messaging.FirebaseMessaging { *; }
`

It might be the case to update manual, or am I doing something wring?

**Comment by Selligent** [comment]
Hi,

Indeed you are right, we'll update the documentation.
Thanks!

For any other question, it is better to contact Selligent directly as this channel is not monitored regularly (hence the very late answer, sorry for that).

Kind regards,
Frédéric
